export function brawlersName(data){
    if(data === 'SHELLY') return '雪莉'
    else if(data === 'COLT') return '柯尔特'
    else if(data === 'BULL') return '公牛'
    else if(data === 'BROCK') return '布洛克'
    else if(data === 'RICO') return '瑞科'
    else if(data === 'SPIKE') return '斯派克'
    else if(data === 'BARLEY') return '巴利'
    else if(data === 'JESSIE') return '杰西'
    else if(data === 'DYNAMIKE') return '爆破麦克'
    else if(data === 'EL PRIMO') return '艾尔·普里莫'
    else if(data === 'MORTIS') return '莫提斯'
    else if(data === 'CROW') return '乌鸦'
    else if(data === 'POCO') return '波克'
    else if(data === 'BO') return '阿渤'
    else if(data === 'PIPER') return '佩佩'
    else if(data === 'PAM') return '帕姆'
    else if(data === 'TARA') return '塔拉'
    else if(data === 'DARRYL') return '达里尔'
    else if(data === 'PENNY') return '潘妮'
    else if(data === 'FRANK') return '弗兰肯'
    else if(data === 'GENE') return '吉恩'
    else if(data === 'TICK') return '迪克'
    else if(data === 'LEON') return '里昂'
    else if(data === 'ROSA') return '罗莎'
    else if(data === 'CARL') return '卡尔'
    else if(data === 'BIBI') return '比比'
    else if(data === '8-BIT') return '8比特'
    else if(data === 'SANDY') return '沙迪'
    else if(data === 'BEA') return '贝亚'
    else if(data === 'EMZ') return '艾魅'
    else if(data === 'MR. P') return 'P先生'
    else if(data === 'MAX') return '麦克斯'
    else if(data === 'JACKY') return '雅琪'
    else if(data === 'GALE') return '格尔'
    else if(data === 'NANI') return '纳妮'
    else if(data === 'SPROUT') return '芽芽'
    else if(data === 'SURGE') return '瑟奇'
    else if(data === 'COLETTE') return '科莱特'
    else if(data === 'AMBER') return '琥珀'
    else if(data === 'LOU') return '小罗'
    else if(data === 'BYRON') return '拜伦'
    else if(data === 'EDGAR') return '艾德加'
    else if(data === 'COLONEL RUFFS') return '拉夫上校'
    else if(data === 'STU') return '斯图'
    else if(data === 'BELLE') return '贝尔'
    else if(data === 'SQUEAK') return '史魁克'
    else if(data === 'GROM') return '格罗姆'
    else if(data === 'BUZZ') return '巴兹'
    else if(data === 'GRIFF') return '格里夫'
    else if(data === 'ASH') return '阿拾'
    else if(data === 'MEG') return '梅格'
    else if(data === 'LOLA') return '萝拉'
    else if(data === 'FANG') return '阿方'
    else if(data === 'NITA') return '妮塔'
    else if(data === 'EVE') return '伊芙'
    else if(data === 'JANET') return '珍妮特'
    else if(data === 'BONNIE') return '邦妮'
}
